### ISSUE TITLE
Calibre installation

### ISSUE THREAD

**Issue by lb803** [OpenBookPublishers/obp-gen-mobi#1]
Is there a pressing reason why (in the `Dockerfile`) we install calibre via an .sh script instead of using apt-get?

**Comment by ja573** [comment]
> Is there a pressing reason why (in the `Dockerfile`) we install calibre via an .sh script instead of using apt-get?

Just so that we can pin the version

**Comment by lb803** [comment]
OK, fantastic!

**Comment by ja573** [comment]
> OK, fantastic!

At least that was the idea. I haven't looked at what the script does - so there might better ways to install it

**Comment by lb803** [comment]
OK, so the script installs the latest version available, here is the little routine which retrieve the latest version number:
```
def check_version():
    global calibre_version
    if calibre_version == '%version':
        calibre_version = urlopen('http://code.calibre-ebook.com/latest').read()
```
How about we replace the installation script with something like: `apt-get install calibre=3.39.1+dfsg-3`?
(3.39.1 is the current stable version in debian, and it works just fine with the the current version of `obp-gen-mobi`).

**Comment by ja573** [comment]
> OK, so the script installs the latest version available, here is the little routine which retrieve the latest version number:
> 
> ```
> def check_version():
>     global calibre_version
>     if calibre_version == '%version':
>         calibre_version = urlopen('http://code.calibre-ebook.com/latest').read()
> ```
> 
Let's avoid this as we want to control (and know) what's installed.

> How about we replace the installation script with something like: `apt-get install calibre=3.39.1+dfsg-3`?
> (3.39.1 is the current stable version in debian, and it works just fine with the the current version of `obp-gen-mobi`).

This sounds good to me
